## -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

def build(bld):
    udppossion = bld.create_ns3_module('udp-possion', ['core','network','internet'])
    udppossion.source = [
        'model/possionsender.cc',
        'model/possionreceiver.cc',
        'model/possiontrace.cc',
        ]
    headers = bld(features='ns3header')
    headers.module = 'udp-possion'
    headers.source = [
        'model/possionsender.h',
        'model/possionreceiver.h',
        'model/possiontrace.h',
        ]
